version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    networks:
      - my-network
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
    networks:
      - my-network
networks:
  my-network:
    driver: bridge
